<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Coworkee.OData\Coworkee.OData.csproj" />
    <ProjectReference Include="..\Coworkee.Storage\Coworkee.Storage.csproj" />
    <ProjectReference Include="..\Coworkee.Identity\Coworkee.Identity.csproj" />
  </ItemGroup>
</Project>
