<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Coworkee.Core\Coworkee.Core.csproj" />
    <ProjectReference Include="..\Coworkee.Domain\Coworkee.Domain.csproj" />
    <ProjectReference Include="..\Coworkee.Contracts\Coworkee.Contracts.csproj" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
</Project>
