<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Coworkee.Settings\Coworkee.Settings.csproj" />
    <ProjectReference Include="..\Coworkee.AspNetCore\Coworkee.AspNetCore.csproj" />
    <PackageReference Include="Anthropic" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <ProjectReference Include="..\Coworkee.OData\Coworkee.OData.csproj" />
  </ItemGroup>
</Project>
