<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Coworkee.Application\Coworkee.Application.csproj" />
    <ProjectReference Include="..\Coworkee.Contracts\Coworkee.Contracts.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Asp.Versioning.Http" />
  </ItemGroup>
</Project>
