<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Coworkee.Core\Coworkee.Core.csproj" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>
</Project>
