<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MyApp.Web.Client\MyApp.Web.Client.csproj" />
    <ProjectReference Include="..\MyApp.ServiceDefaults\MyApp.ServiceDefaults.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <CoworkeePackage Include="Coworkee.Bff" />
  </ItemGroup>
</Project>
