<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Coworkee.Social\Coworkee.Social.csproj" />
    <ProjectReference Include="..\..\src\Coworkee.Identity\Coworkee.Identity.csproj" />
    <ProjectReference Include="..\..\src\Coworkee.Testing\Coworkee.Testing.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
  </ItemGroup>
</Project>
