<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>true</IsPackable>
    <Authors>fgilde</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/fgilde/CoworkeeLib</PackageProjectUrl>
    <RepositoryUrl>https://github.com/fgilde/CoworkeeLib</RepositoryUrl>
    <Description>Coworkee application framework – $(MSBuildProjectName)</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../assets/icon.png" Pack="true" PackagePath="/" Visible="false" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
  </ItemGroup>
</Project>
