<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Coworkee.Files\Coworkee.Files.csproj" />
    <ProjectReference Include="..\..\src\Coworkee.Identity\Coworkee.Identity.csproj" />
    <ProjectReference Include="..\..\src\Coworkee.Testing\Coworkee.Testing.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>
</Project>
